// AssertError tests
//
// AssertError inherits its methods from Error.

function testInitializer_noFrames() {
    skip("Pending stack trace cleanup completion.");
    var err = AssertError("Failure");
    check(err.message()).eq("Failure");
    check(err.stackFrames()).isEmpty();
}

function testInitializer_frames() {
    skip("Pending stack trace cleanup completion.");
    var err = AssertError("Failure", "A", "B");
    check(err.message()).eq("Failure");
    check(err.stackFrames()).eq(List("A", "B"));
}

function testCanThrow() {
    var err = AssertError("Failure", "A", "B");
    checkCatch(\-> { throw err; })
        .message("Failure");
}

